import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import dts from 'unplugin-dts/vite';
import ui from '@nuxt/ui/vite'
import { resolve } from 'path';
import sassDts from 'vite-plugin-sass-dts'


/** @type {import('vite').UserConfig} */
export default defineConfig({
  plugins: [
    vue(),
    dts({
      insertTypesEntry: true,
      bundleTypes: true,
      processor: 'vue',
      entryRoot: 'src',
      tsconfigPath: './tsconfig.json',
    }),
    ui(),
    sassDts(),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'ProjectAngusLastfm',
      fileName: (format) => `project-angus-lastfm.${format}.js`,
    },
    rollupOptions: {
      external: [
        'vue', 
        'ky',
      ],
      output: {
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});
